#!/bin/bash
## disks py3status output

dfroot=$(df -h | grep sdb2 | tr -s ' ' | cut -d' ' -f 4 | sed 's/[^0-9]//g')
dfhome=$(df -h | grep sdb3 | tr -s ' ' | cut -d' ' -f 4 | sed 's/[^0-9]//g')

echo $dfroot
echo $dfhome

echo $((dfroot + dfhome))GB
